dev/src/carts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import(
    cart_home,
    cart_update
)

urlpatterns = [
    url(r'^$',cart_home,name="home"),
    #url(r'^(?P<slug>[\w-]+)/$', product_list),
    url(r'^update/$',cart_update,name='update'),
    ]

dev/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url,include
from django.contrib import admin

"""from products.views import(
                ProductListView,
                product_list_view,
                ProductDetailView,
                product_detail_view,
                ProductFeaturedView,
                ProductFeaturedDetailView,
                ProductDetailSlugView



)
"""


from .views import home_page,about_page,contact_page,login_page,register_page
from carts.views import cart_home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^about/$', about_page,name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^login/$', login_page,name='login'),
    url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^register/$', register_page,name='register'),
    url(r'^products/',include("products.urls", namespace="products")),
    url(r'^search/',include("search.urls", namespace="search"))
    #url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', product_list_view),
    #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
   # url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    #url(r'^products-featured/$', ProductFeaturedView.as_view()),
    #url(r'^products-detail-featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/src/products/urls.py
from django.conf.urls import url
from django.contrib import admin
from products.views import(
                ProductListView,
                ProductDetailSlugView,
                product_list,
                product_detail_view

)

urlpatterns = [
    url(r'^$', ProductListView.as_view(),name="list"),
    #url(r'^(?P<slug>[\w-]+)/$', product_list),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(),name='detail'),
    ]

dev/src/search/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
    SearchProductView,
                )

urlpatterns = [
    url(r'^$', SearchProductView.as_view(),name="query"),
    ]

dev/src/templates/base/css.html
 {% load static %}

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

dev/src/templates/base/js.html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

dev/src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'products:list' as product_url %}
{% load staticfiles %}

<head>
<title>Ecom</title>
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css'%}"/>
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">

<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static 'styles/bootstrap4/popper.js'%}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js'%}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js'%}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js'%}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js'%}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js'%}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js'%}"></script>
<script src="{% static 'plugins/easing/easing.js'%}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{% static 'js/custom.js'%}"></script>
</head>

<div>


  


<hearder class="header">
    <div class="header_container">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="header_content d-flex flex-row align-items-center justify-content-start">
              <div class="logo"><a href="{{home_url}}">{{brand_name}}</a></div>
              <nav class="main_nav">
                <ul>
                  <li class="{% if request.path == home_url %}active{% endif %}"><a href="{{home_url}}">Home</a></li>
                  <li class="{% if request.path == product_url %}active{% endif %}"><a href="{{product_url}}">Products</a></li>
                  <li class="{% if request.path == about_url %}active{% endif %}"><a href="{{about_url}}">About</a></li>
                  <li class="{% if request.path == contact_url %}active{% endif %}"><a href="{{contact_url}}">Contact</a></li>
                  <li class="{% if request.path == register_url %}active{% endif %}"><a href="{{register_url}}">Register</a></li>
                  {% if request.user.is_authenticated %}
                  <li ><a href="{{login_url}}">Logout</a></li>
                  {% else %}
                  <li class="{% if request.path == login_url %}active{% endif %}"><a href="{{login_url}}">Login</a></li>
                  {% endif %}
                  
                </ul>
              </nav>
              <div class="header_extra ml-auto">
                <div class="shopping_cart {% if request.path == product_url %}active{% endif %}">
                  <a href="{{cart_url}}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                         viewBox="0 0 489 489" style="enable-background:new 0 0 489 489;" xml:space="preserve">
                      <g>
                        <path d="M440.1,422.7l-28-315.3c-0.6-7-6.5-12.3-13.4-12.3h-57.6C340.3,42.5,297.3,0,244.5,0s-95.8,42.5-96.6,95.1H90.3
                          c-7,0-12.8,5.3-13.4,12.3l-28,315.3c0,0.4-0.1,0.8-0.1,1.2c0,35.9,32.9,65.1,73.4,65.1h244.6c40.5,0,73.4-29.2,73.4-65.1
                          C440.2,423.5,440.2,423.1,440.1,422.7z M244.5,27c37.9,0,68.8,30.4,69.6,68.1H174.9C175.7,57.4,206.6,27,244.5,27z M366.8,462
                          H122.2c-25.4,0-46-16.8-46.4-37.5l26.8-302.3h45.2v41c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h139.3v41
                          c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h45.2l26.9,302.3C412.8,445.2,392.1,462,366.8,462z"/>
                      </g>
                    </svg>
                    <div>Cart <span>({{request.session.cart_items}})</span></div>
                  </a>
                </div>
                <div class="search">
                  <div class="search_icon">
                    <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 475.084 475.084" style="enable-background:new 0 0 475.084 475.084;"
                     xml:space="preserve">
                    <g>
                      <path d="M464.524,412.846l-97.929-97.925c23.6-34.068,35.406-72.047,35.406-113.917c0-27.218-5.284-53.249-15.852-78.087
                        c-10.561-24.842-24.838-46.254-42.825-64.241c-17.987-17.987-39.396-32.264-64.233-42.826
                        C254.246,5.285,228.217,0.003,200.999,0.003c-27.216,0-53.247,5.282-78.085,15.847C98.072,26.412,76.66,40.689,58.673,58.676
                        c-17.989,17.987-32.264,39.403-42.827,64.241C5.282,147.758,0,173.786,0,201.004c0,27.216,5.282,53.238,15.846,78.083
                        c10.562,24.838,24.838,46.247,42.827,64.234c17.987,17.993,39.403,32.264,64.241,42.832c24.841,10.563,50.869,15.844,78.085,15.844
                        c41.879,0,79.852-11.807,113.922-35.405l97.929,97.641c6.852,7.231,15.406,10.849,25.693,10.849
                        c9.897,0,18.467-3.617,25.694-10.849c7.23-7.23,10.848-15.796,10.848-25.693C475.088,428.458,471.567,419.889,464.524,412.846z
                         M291.363,291.358c-25.029,25.033-55.148,37.549-90.364,37.549c-35.21,0-65.329-12.519-90.36-37.549
                        c-25.031-25.029-37.546-55.144-37.546-90.36c0-35.21,12.518-65.334,37.546-90.36c25.026-25.032,55.15-37.546,90.36-37.546
                        c35.212,0,65.331,12.519,90.364,37.546c25.033,25.026,37.548,55.15,37.548,90.36C328.911,236.214,316.392,266.329,291.363,291.358z
                        "/>
                    </g>
                  </svg>
                  </div>
                </div>
                <div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Search Panel -->
    <div class="search_panel trans_300">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="search_panel_content d-flex flex-row align-items-center justify-content-end">
              <form method="GET" action="{% url 'search:query' %}">
                <input type="text" class="search_input" placeholder="Search" required="required" name="q" value="{{request.GET.q}}">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Social -->
  </header>

  <div class="menu menu_mm trans_300">
    <div class="menu_container menu_mm">
      <div class="page_menu_content">
              
        <div class="page_menu_search menu_mm">
          <form action="#">
            <input type="search" required="required" class="page_menu_search_input menu_mm" placeholder="Search for products...">
          </form>
        </div>
        <ul class="page_menu_nav menu_mm">
          <li class="page_menu_item menu_mm"><a href="{{home_url}}">Home<i class="fa fa-angle-down"></i></a></li>
          <li class="page_menu_item menu_mm"><a href="{{product_url}}">Products<i class="fa fa-angle-down"></i></a></li>
          <li class="page_menu_item menu_mm"><a href="{{about_url}}">About<i class="fa fa-angle-down"></i></a></li>
          <li class="page_menu_item menu_mm"><a href="{{contact_url}}">contact<i class="fa fa-angle-down"></i></a></li>
          <li class="page_menu_item menu_mm"><a href="{{register_url}}">Register<i class="fa fa-angle-down"></i></a></li>
          {% if request.user.is_authenticated %}
          <li class="page_menu_item menu_mm"><a href="{{login_url}}">logout<i class="fa fa-angle-down"></i></a></li>
          {% else %}
          <li class="page_menu_item menu_mm"><a href="{{login_url}}">Login<i class="fa fa-angle-down"></i></a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="menu_close"><i class="fa fa-times" aria-hidden="true"></i></div>

  </div>


  <!-- Menu -->

  